### PR TITLE
PEP008 fixes to nlinsolve

### PR DESCRIPTION
**Pull request by kshitij10496**
Ping @Shekharrajak

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Thanks. Which text editor do you use ?

**Comment by Shekharrajak** [comment]
Ah ! I did some mistake. Need to revert, right now.

**Comment by Shekharrajak** [comment]
I pushed some commits, but it is not showing in PR.

**Comment by kshitij10496** [comment]
I think you will have to do the following:
1. Fetch the branch `gsoc_nlinsolve` from `origin` (your remote).  
   `git fetch origin`
2. Checkout your local branch `gsoc_nlinsolve`  
   `git checkout gsoc_nlinsolve`
3. Merge the branches  
   `git merge origin/gsoc_nlinsolve`
4. Push it back to `origin`.  
   `git push origin gsoc_nlinsolve`

This will update the PR with the new commits.

**Comment by Shekharrajak** [comment]
Yeah, I did similar things. After `rebase` and force push, it is taking some time.

**Pull request merged**
